### ISSUE TITLE
Share materials of solving minesweeper 

### ISSUE THREAD

**Issue by NoxSensei** [Project-Summer-AI-Lab-Glider/infinite-minesweeper-ui#1]

**Comment by mslazynski** [comment]
# Penrose tilings:

- http://www.math.ubc.ca/~cass/courses/m308-02b/projects/schweber/penrose.html - basic explanation of the Penrose tiling generation
- http://www.math.utah.edu/~treiberg/PenroseSlides.pdf - different types of tilings and explanation why it's not easy to generate penrose tilings incrementally
- https://scipython.com/blog/penrose-tiling-1/ - python code (with explanations) generating a Penrose tiling
- https://math.stackexchange.com/questions/3465244/properly-drawing-a-penrose-tiling-using-the-pentagrid-method - nice post on a less popular (but maybe better suited for our problem) algorithm to draw a Penrose tiling

# Solving minesweeper

- https://magnushoff.com/articles/minesweeper/ - one can read a bit about resolving only local constraints vs solving them globally
- http://mrgris.com/projects/minesweepr - a short page about a minesweeper solver, includes source code in Python 2.7
- https://dspace.cvut.cz/bitstream/handle/10467/68632/F3-BP-2017-Cicvarek-Jan-Algorithms%20for%20Minesweeper%20Game%20Grid%20Generation.pdf - a bachelor thesis on minefield generation
- https://yurichev.com/writings/SAT_SMT_by_example.pdf - this document has a chapter dedicated to solving minesweeper with SAT/SMT solver
- https://github.com/hakank/hakank/blob/master/minizinc/minesweeper.mzn - minesweeper model in MiniZinc
- https://cmears.id.au/articles/mines-solver.html - using MiniZinc to solve deterministic minesweeper

Important note: most of the algorithm out there try to cope with the situation where:

- one may have to guess 
- one knows how many mines are left to be found
- also one can have to disjoint uncovered sets of mines

None of those assumptions is true in our case.

# Related projects:

- https://pwmarcz.pl/blog/kaboom/ - sometimes player really has to guess but in such a case he always is lucky ;) 
- https://www.chiark.greenend.org.uk/~sgtatham/puzzles/js/mines.html - a deterministic minesweeper
- https://minesweeper-multiplayer.dk/ - minesweeper with a twist, that players share one big minefield
- https://cdn.warpedmines.com/ - minesweeper in alternative geometries, btw - the minesweeper in hyperbolic world is much simpler: https://arxiv.org/pdf/2002.09534v1.pdf
